### ISSUE TITLE
Roary gene_Presence_Absence.csv file is not being displayed

### ISSUE THREAD

**Issue by LilCros** [jameshadfield/phandango#138]
Hello,
I did perform Roary Pan Genome analysis on my data using the GALAXY platform. However the Gene_Presence_Absence.csv file is not being displayed despite the tree and the metadata files are.
Could you please advice? I am not sure if there could be something wrong with the csv file.
Best,
Lil

**Comment by jameshadfield** [comment]
Hi @LilCros - Could you try using these datasets: https://github.com/jameshadfield/phandangoExampleData/tree/master/roary_S.Weltevreden to work out if it's a problem with Phandango (in your browser) or your particular files?

**Comment by LilCros** [comment]
Hi Jason,
I will try with these datasets and let you know.
Thank you,
Francy

Francy Liliana Crosby PhD
Research Assistant Professor
University of Florida
College of Veterinary Medicine
Academic Buildg, Second floor, room V2-200
Office phone # 352-294-4182
Laboratory Phone # 352-294-4134
Email: ***@***.***

**Comment by LilCros** [comment]
Hello James,
I downloaded the files you kindly sent me and everything is working fine.
Do you think is something wrong with my files. Please see https://github.com/LilCros/Ap-Roary
Thank you,
Francy

**Comment by jameshadfield** [comment]
Thanks - in your ROARY CSV, the first line contains strings such as`"ApBov1_FRA:gff"`, `"ApCRT35_MN:gff"` etc. They shouldn't have the trailing `:gff`. If you do a simple find & replace to remove `:gff` from the file (only appears in the first line) then it works:

![image](https://user-images.githubusercontent.com/8350992/127918204-6e1c36fd-16c3-401a-8d66-7b3734759501.png)

(It's been a _long_ time since I looked at these files, so I don't know what is causing this, or what this may mean.)

**Comment by LilCros** [comment]
Excellent!
I would do the changes form the file.
Again, thank you for your time,
Lil

Francy Liliana Crosby Ph.D
Research Assistant Professor
Department of Infectious Diseases and Immunology
University of Florida|College of Veterinary Medicine
(352) 294 4182 (Office)
(352 294 4134 (Laboratory)
